name: Build

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      zipped:
        description: 'If true, outputs double-zipped artifacts (for releases)'
        default: false
        required: false
        type: boolean
  push:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        selfcontained: [true, false]
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Build
      run: dotnet publish PTVersionDownloader.csproj -c Release -r win-x86 --self-contained ${{matrix.selfcontained}} -p:PublishSingleFile=True --output release-${{matrix.selfcontained}}/
    
    - name: Create zip
      if: ${{inputs.zipped == true}}
      run: |
        7z a -tzip PTVersionDownloader${{matrix.selfcontained == true && '-self-contained' || ''}}.zip ./release-${{matrix.selfcontained}}/*
    - name: Upload artifact (zipped)
      if: ${{inputs.zipped == true}}
      uses: actions/upload-artifact@v4.6.2
      with:
        name: PTVersionDownloader${{matrix.selfcontained == true && '-self-contained' || ''}}
        path: PTVersionDownloader${{matrix.selfcontained == true && '-self-contained' || ''}}.zip
    
    - name: Upload artifact (unzipped)
      if: ${{inputs.zipped != true}}
      uses: actions/upload-artifact@v4.6.2
      with:
        name: PTVersionDownloader${{matrix.selfcontained == true && '-self-contained' || ''}}
        path: release-${{matrix.selfcontained}}/*
