name: Release

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      zipped: true
  release:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4.2.1
        with:
          merge-multiple: true
          
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout: PTVersionDownloader.csproj
          
      - name: Get version
        id: package_version
        uses: KageKirin/get-csproj-version@v1.0.0
        with:
          file: PTVersionDownloader.csproj
          regex: "^(?<major>\\d+\\.\\d+\\.\\d+\\.\\d+)$"
          xpath: //PropertyGroup/AssemblyVersion
      
      - name: GH Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: v${{ steps.package_version.outputs.version }}
          draft: true
          files: "*.zip"
          fail_on_unmatched_files: true
